name: Auto Release Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      VERSION: ''

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Version
        id: set_version
        shell: pwsh
        run: |
          $pkgPath = "wtyczka/package.json"
          $pkg = Get-Content $pkgPath -Raw | ConvertFrom-Json
          $version = $pkg.version
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Delete Old Release and Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "v$env:VERSION" --yes || true
          git push origin --delete "v$env:VERSION" || true

      - name: Install dependencies
        working-directory: wtyczka
        run: npm install

      - name: Build Extension
        working-directory: wtyczka
        run: npm run build

      - name: Copy README
        run: Copy-Item "README.md" "wtyczka/build/chrome-mv3-prod/README.md" -Force

      - name: Package Release zip
        shell: pwsh
        run: |
          if (Test-Path "AntiTestportal-v$env:VERSION.zip") { Remove-Item "AntiTestportal-v$env:VERSION.zip" }
          Compress-Archive -Path "wtyczka/build/chrome-mv3-prod/*" -DestinationPath "AntiTestportal-v$env:VERSION.zip" -Force

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "AntiTestportal+ v${{ env.VERSION }}"
          files: AntiTestportal-v${{ env.VERSION }}.zip
          generate_release_notes: false
          body: "Automatycznie wygenerowana nowa wersja AntiTestportal+ ulepszona przez system Auto-Release. Aby zaktualizować wtyczkę pobierz najnowszy plik ZIP, wypakuj i wgraj od nowa w Chrome/Edge."
